services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # O comando para iniciar a aplicação é herdado do Dockerfile.
    # A flag --reload é ótima para desenvolvimento, pois reinicia o servidor
    # automaticamente quando detecta alterações no código.